/**
 * Claim page for recipients to claim messages without a wallet
 * Requirements: 6.6
 * 
 * This page is accessible via claim links generated by senders.
 * Recipients enter a passphrase to decrypt and claim their message.
 */

'use client';

import { use } from 'react';
import { ClaimInterface } from '@/components/redeem';
import type { DecryptedRedeemPackage } from '@/types/redeem';

interface ClaimPageProps {
  params: Promise<{
    packageCID: string;
  }>;
}

export default function ClaimPage({ params }: ClaimPageProps) {
  const { packageCID } = use(params);

  const handleClaimed = (redeemPackage: DecryptedRedeemPackage) => {
    // Store the claimed package info in localStorage for the dashboard
    try {
      const claimedMessages = JSON.parse(
        localStorage.getItem('claimedMessages') || '[]'
      );
      
      claimedMessages.push({
        packageCID,
        encryptedKeyCID: redeemPackage.encryptedKeyCID,
        encryptedMessageCID: redeemPackage.encryptedMessageCID,
        messageHash: redeemPackage.messageHash,
        unlockTimestamp: redeemPackage.unlockTimestamp,
        sender: redeemPackage.sender,
        claimedAt: Date.now(),
      });

      localStorage.setItem('claimedMessages', JSON.stringify(claimedMessages));
    } catch (err) {
      console.error('Failed to save claimed message:', err);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            FutureProof
          </h1>
          <p className="text-gray-600">
            Guaranteed by math, not corporations
          </p>
        </div>

        {/* Claim Interface */}
        <ClaimInterface packageCID={packageCID} onClaimed={handleClaimed} />

        {/* Info Section */}
        <div className="mt-8 text-center text-sm text-gray-500">
          <p>
            FutureProof uses client-side encryption and blockchain technology
          </p>
          <p>to ensure your messages remain private and time-locked.</p>
        </div>
      </div>
    </div>
  );
}
